name: Docker Image CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: senaarth/gces-trabalho-2022-1/.github/workflows/ci.yml@main
  deploy:
    name: Docker Image
    runs-on: ubuntu-latest  
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: senaarth/gces-library:latest
