name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: POSTGRES_ENV
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker-compose build
